-- ============================================================
-- LLHAMA Database Initialization Script
-- ============================================================
-- This script creates the complete database schema for Local_LLHAMA
-- Run this as the llhama_usr role after creating the database
-- 
-- Usage:
--   psql -U llhama_usr -d llhama -f init_database.sql
-- ============================================================

-- Drop existing tables if they exist (for clean reinstall)
DROP TABLE IF EXISTS message_embeddings CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS conversations CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Drop sequences if they exist
DROP SEQUENCE IF EXISTS users_id_seq CASCADE;
DROP SEQUENCE IF EXISTS events_id_seq CASCADE;

-- ============================================================
-- TABLE: users
-- ============================================================
-- Stores user accounts with authentication and permissions
CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP WITHOUT TIME ZONE,
    is_active BOOLEAN DEFAULT true,
    is_admin BOOLEAN DEFAULT false,
    can_access_dashboard BOOLEAN DEFAULT true,
    can_access_chat BOOLEAN DEFAULT true,
    must_change_password BOOLEAN DEFAULT false
);

-- Create index on username for faster lookups
CREATE INDEX idx_username ON users(username);

-- ============================================================
-- TABLE: conversations
-- ============================================================
-- Stores chat conversation threads
CREATE TABLE conversations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    title TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- ============================================================
-- TABLE: messages
-- ============================================================
-- Stores individual messages within conversations
CREATE TABLE messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID REFERENCES conversations(id) ON DELETE CASCADE,
    role TEXT CHECK (role IN ('user', 'assistant', 'system')),
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- ============================================================
-- TABLE: message_embeddings
-- ============================================================
-- Stores vector embeddings for semantic search
-- Requires pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE message_embeddings (
    message_id UUID PRIMARY KEY REFERENCES messages(id) ON DELETE CASCADE,
    vector vector(768)  -- Adjust dimension based on your embedding model
);

-- ============================================================
-- TABLE: events
-- ============================================================
-- Stores calendar events, reminders, appointments, alarms, and tasks
CREATE TABLE events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    description TEXT,
    event_type TEXT NOT NULL CHECK (event_type IN ('reminder', 'appointment', 'alarm', 'task', 'event')),
    due_datetime TEXT NOT NULL,
    repeat_pattern TEXT CHECK (repeat_pattern IN ('none', 'daily', 'weekly', 'monthly', 'yearly')),
    is_completed BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    completed_at TEXT,
    notification_minutes_before INTEGER DEFAULT 0
);

-- Create indexes for faster queries
CREATE INDEX idx_user_id ON events(user_id);
CREATE INDEX idx_event_type ON events(event_type);
CREATE INDEX idx_due_datetime ON events(due_datetime);
CREATE INDEX idx_is_completed ON events(is_completed);

-- ============================================================
-- DEFAULT ADMIN USER
-- ============================================================
-- Insert default admin user
-- Username: admin
-- Password: admin123 (CHANGE THIS AFTER FIRST LOGIN!)
-- Password hash generated with bcrypt
INSERT INTO users (username, password_hash, is_admin, is_active, can_access_dashboard, can_access_chat, must_change_password)
VALUES ('admin', '$2a$06$GAxMWtXLsMvbB6yS5FGAT.9mnEwYNjxNAUEuOFHLsAicnQmxEXQVa', true, true, true, true, true);

-- ============================================================
-- PERMISSIONS
-- ============================================================
-- Grant necessary permissions to llhama_usr
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO llhama_usr;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO llhama_usr;

-- Set default privileges for future objects
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO llhama_usr;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO llhama_usr;

-- ============================================================
-- COMPLETION MESSAGE
-- ============================================================
\echo '============================================================'
\echo 'Database initialization complete!'
\echo '============================================================'
\echo 'Tables created: users, conversations, messages, message_embeddings, events'
\echo 'Default admin user: admin / admin123'
\echo 'IMPORTANT: Change the admin password after first login!'
\echo '============================================================'
