name: Documentation Issue
description: Report an issue with documentation or suggest improvements
title: "[DOCS] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!
  
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - README
        - Wiki
        - Code Comments
        - Setup Instructions
        - API Documentation
        - Configuration Guide
        - Other
    validations:
      required: true
  
  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What's wrong with the current documentation?
      placeholder: The documentation for X is unclear because...
    validations:
      required: true
  
  - type: input
    id: location
    attributes:
      label: Location
      description: Where is this documentation located?
      placeholder: e.g., README.md line 123, Wiki page "Setup"
  
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: It should explain...
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or examples
